import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/config/providers";
import * as api from "@/lib/api";
import SiteHeader from "@/components/site-header";
import { Toaster } from "sonner";
import { auth } from "@/auth";
import { useQuery } from "@tanstack/react-query";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [session, categories] = await Promise.all([
    auth(),
    api.getAllCategories(),
  ]);

  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-7xl mx-auto`}
      >
        <Providers>
          <SiteHeader session={session} categories={categories.data ?? []} />
          <main>{children}</main>
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
